### ISSUE TITLE
502 Gateway Error - Nginx

### ISSUE THREAD

**Issue by amitk79** [retspen/webvirtmgr#222]
When we clone or launch a new instance from templates, After sometime it gives 502 error on Nginx. I have increased proxy read and timeout but still same. It seems it is timeout issue from backend. Can you please confirm ?

Thanks for  awesome product.

**Comment by Expert-Newbie** [comment]
Hello,

Just in case you are using Webvirtmgr behind a proxy nginx.

**Solution :**
I had to change `DEBUG = TRUE` to `DEBUG = True` in  /var/www/webvirtmgr/webvirtmgr/settings.py
then `systemctl stop supervisord.service` and `systemctl start supervisord.service` and finally `systemctl restart nginx`  and it works !

**Explanation :**
The problem doesn't come from nginx but from the service behind the port (in my case port 8000) that nginx redirect on.
I used the log with `systemctl status supervisord.service -l`  and i had an error with python.
This link help me to find the solution : [https://stackoverflow.com/questions/30095032/nameerror-name-true-is-not-defined](url)

Hope it works for you too !
