### ISSUE TITLE
webvirtmgr not working

### ISSUE THREAD

**Issue by jaydeepch15** [retspen/webvirtmgr#241]
My KVM and webvirtmgr is installed on same server (CentOS 6.5)

followed below link to install webvirtmgr
https://github.com/retspen/webvirtmgr/wiki/Install-WebVirtMgr

Getting same error
Failed to connect to server (code: 1006)

When I run
[root@kvm ~]# websockify 6080 10.10.8.107:5900
WebSocket server settings:

```
Listen on :6080
Flash security policy server
No SSL/TLS support (no cert file) Traceback (most recent call last): File "/usr/bin/websockify", line 9, in load_entry_point('websockify==0.4.1', 'console_scripts', 'websockify')() File "/usr/lib/python2.6/site-packages/websockify/websocketproxy.py", line 390, in websockify_init server.start_server() File "/usr/lib/python2.6/site-packages/websockify/websocket.py", line 834, in start_server lsock = self.socket(self.listen_host, self.listen_port, False, self.prefer_ipv6) File "/usr/lib/python2.6/site-packages/websockify/websocket.py", line 198, in socket sock.bind(addrs[0][4]) File "", line 1, in bind socket.error: [Errno 98] Address already in use
```

Removed comment in /etc/libvirt/qemu.conf file, then restart libvirted service.
vnc_listen = "0.0.0.0"
&
remote_display_port_min = 5900
remote_display_port_max = 65535

FYI

I haven't created VM from Webvirtmgr, I had created it from backend

[root@kvm ~]# virt-install --connect qemu:///system -n vm10 -r 1024 --vcpus=2 --disk path=/var/lib/libvirt/images/vm10.img,size=12 -c /dev/sr0 --vnc --noautoconsole --os-type windows --os-variant win7 --accelerate --network=bridge:br0 --hvm

**Comment by johnerramirez** [comment]
didn't help
I still cannot connect to console

**Comment by johnerramirez** [comment]
this is my error

Failed to connect to server (code: 1006)

**Comment by johnerramirez** [comment]
Im using a CentOS 6.7

**Comment by johnerramirez** [comment]
[root@WebVirtMgr initd]# yum list installed | grep novnc
novnc.noarch           0.5.1-2.el6      @epel
