### ISSUE TITLE
create storage pool from webvirtmgr interface

### ISSUE THREAD

**Issue by Hemo1234** [retspen/webvirtmgr#252]
I have tried to create new pool, but there is no way i can add my OS image

in DIR the path is : /var/lib/libvirt/images
and IOS : /var/www/webvirtmgr/images
when i tired to create ISO it says " cannot open path '/var/www/webvirtmgr/images': No such file or directory"
please how to slove this issue.

Thank you

**Comment by captain4dmin** [comment]
I try to create lvm storage and when I test with 
Name -->  Data
Device --> /dev/sda5   (or just sda5 where sda5 is my pv)

I have this message:
The target must not contain any special characters

**Comment by rgombash** [comment]
@captain4dmin : you have to define storage pool in libvirt on your host. Here is how:
virsh pool-define-as lv_guest_vm logical --source-name [VG name] --target [path to VG location on disk]
After this you will see your VG listed in storages and you can add new LV's manually or by instancing new vm's to this pool (this will create LV that is same name as new virtual machine)

**Comment by captain4dmin** [comment]
All is ok, 

pvremove /dev/sda5
Then I create the lvm space via web interface and it's ok

thanks
