### ISSUE TITLE
webvirtmgr is not starting after the upgrade

### ISSUE THREAD

**Issue by jefferyb** [retspen/webvirtmgr#292]
After the upgrade, I get and try to go to http://foo.example.com:8000, I get:

```
MOD_PYTHON ERROR

ProcessId:      22915
Interpreter:    'foo.example.com'

ServerName:     'foo.example.com'
DocumentRoot:   '/var/www/webvirtmgr'

URI:            '/'
Location:       None
Directory:      None
Filename:       '/var/www/webvirtmgr/'
PathInfo:       ''

Phase:          'PythonHandler'
Handler:        'django.core.handlers.modpython'

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/mod_python/importer.py", line 1537, in HandlerDispatch
    default=default_handler, arg=req, silent=hlist.silent)

  File "/usr/lib/python2.7/dist-packages/mod_python/importer.py", line 1202, in _process_target
    module = import_module(module_name, path=path)

  File "/usr/lib/python2.7/dist-packages/mod_python/importer.py", line 304, in import_module
    return __import__(module_name, {}, {}, ['*'])

ImportError: No module named modpython
```

And I tried moving the /var/www/webvirtmgr directory and do an install using https://github.com/retspen/webvirtmgr/wiki/Install-WebVirtMgr direction, and I still get that error above... 

when I shutdown apache2 ($ service apache2 stop) and try 

```
$ ./manage.py runserver 0:8000
```

then, I can access http://foo.example.com:8000/ fine with no errors...

Here's what's in requirements.txt:

```
    django==1.5.5
    gunicorn==18.0
    # Utility Requirements
    # for SECURE_KEY generation
    lockfile>=0.9
    # Uncoment for support ldap
    #django-auth-ldap==1.2.0
```

I saw this issue: https://github.com/retspen/webvirtmgr/issues/60 and it looks like it was a _"Wrong django release, 1.5.1"_ but I have 1.5.5 from requirements.txt... 

Oh, I'm running Ubuntu 13.04

Maybe I missed something during the install/upgrade??? Any help would be greatly appreciated!!! 
Thanks :)

**Comment by ridolfino** [comment]
Hai scritto il modulo errato, ecco il config corretto:
<VirtualHost *:80>
        # The ServerName directive sets the request scheme, hostname and port that
        # the server uses to identify itself. This is used when creating
        # redirection URLs. In the context of virtual hosts, the ServerName
        # specifies what hostname must appear in the request's Host: header to
        # match this virtual host. For the default virtual host (this file) this
        # value is not decisive as it is used as a last resort host regardless.
        # However, you must set it for any further virtual host explicitly.
        #ServerName www.example.com

        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html

        # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
        # error, crit, alert, emerg.
        # It is also possible to configure the loglevel for particular
        # modules, e.g.
        #LogLevel info ssl:warn

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        # For most configuration files from conf-available/, which are
        # enabled or disabled at a global level, it is possible to
        # include a line for only one particular virtual host. For example the
        # following line enables the CGI configuration for this host only
        # after it has been globally disabled with "a2disconf".
        Include conf-available/serve-cgi-bin.conf
        AddHandler mod_python .py
        PythonHandler mod_python.publisher
        PythonDebug On
</VirtualHost>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
Insertiscilo in /etc/apache2/sites-enable/00-default.conf
Usa apache2 e non cambiare gestore di virtualserver!
