### ISSUE TITLE
Crashes with a specific VM configuration

### ISSUE THREAD

**Issue by romu70** [retspen/webvirtmgr#300]
Don't really know where I did something wrong, but I did. I created and removed few times the same VM and now, there is no way to display the instances list of my server.

The "Infrastructure" link works and this specific VM is visible. But if I click on the server link (so to go to {server}:8000/instances/1, I get a 500 ERROR.

I restarted the supervisor service, same problem. If I remove this VM, no trouble anymore. But I really need it. Think something remains recorded on the HDD even if I delete it. All works fine with virt-manager.

Any help to debug and remove the issue? Thanks.

**Comment by df-cryptostorm** [comment]
Just an FYI, I also noticed this bug when I removed a VM instance from the web interface then tried recreating it with the same name.
Tried removing the VM image file, `virsh destroy`ing it, etc. but the sqlite3 fix above worked.
