### ISSUE TITLE
Method to customise the virtual machine XML template and also set VNC password for webvirtmgr.db

### ISSUE THREAD

**Issue by JJClements** [retspen/webvirtmgr#33]
It would be good to have an easy way (a separate template or config file) specifically for customising the XML template that gets created for each virtual machine through WebVirtMgr. At the moment if anyone wishes to edit how the XML virtual machine config files get created this has to be done by manually making changes to:

/var/www/webvirtmgr/virtmgr/views.py

It would be good to do this through the web interface as well if possible. Another feature would be an option to specify a VNC password in it so that the same password is written to:

/var/www/webvirtmgr/webvirtmgr.db

At the moment I have to change (line 553 of views.py):

vnc_passwd = ''.join([choice(letters + digits) for i in range(12)])
to
vnc_passwd = 'P@ssw0rd'

**Comment by euronck** [comment]
i also bump this
