### ISSUE TITLE
webvirtmgr - interfaces: No local_settings file found.

### ISSUE THREAD

**Issue by labdidi** [retspen/webvirtmgr#376]
Hi,
OS: Debian Wheezy
Libvirt version: 0.9.12.3

Every time when i access the webvirtmgr, i get the following error in the apache error log:

--snip--
[Sun Jul 27 17:38:54 2014] [error] WARNING:root:No local_settings file found.
--snip--

**Comment by Solomoncc** [comment]
- WARNING:root:No local_settings file found.
and the page show me ：
Oops!
500 Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete you request.

**Comment by Solomoncc** [comment]
attempt to write a readonly database
