### ISSUE TITLE
The target must not contain any special characters when choose LVM

### ISSUE THREAD

**Issue by psdrndm** [retspen/webvirtmgr#492]
The target must not contain any special characters when choose LVM for storage

**Comment by sammcj** [comment]
Just encounter this.

https://github.com/retspen/webvirtmgr/blob/master/storages/forms.py#L35

Causes /dev/somedisk to fail because device paths contain slashes.
Suggest removing check for special chars on device paths.

**Comment by retspen** [comment]
Fixed d2ba353ab6b786e031b9a665c315b7d0ebfe9d3e
