### ISSUE TITLE
novnc operation error

### ISSUE THREAD

**Issue by gyuha** [retspen/webvirtmgr#521]
Use fabric install... (ubuntu 14.04)
Don't work novnc..

Error message

> Server disconnected (code: 1006)

i fix it..

```
ln -snf /var/www/webvirtmgr/console/webvirtmgr-console /var/www/webvirtmgr/console/webvirtmgr-novnc
```

/etc/init.d/webvirtmgr-novnc 
application file path  is incorrect.

**Comment by ainoniwa** [comment]
Probably, fabric installer used the old installation way.
Now, webvirtmgr-console run with the supervisor.
(See: https://github.com/retspen/webvirtmgr/wiki/Install-WebVirtMgr / 4. Setup Supervisor)

**Comment by brenard** [comment]
Indeed, it's better to use supervisor. In any case, I prepare a fix in fabric scripts to properly rename webvirtmgr-console script (https://github.com/brenard/webvirtmgr/commit/67119d53a40e9b63e72471c26b34267ffef2d967).

**Comment by brenard** [comment]
@gyuha : My fix was merged. Could you close this issue ?
