### ISSUE TITLE
UX: add fullscreen to the VNC window as button

### ISSUE THREAD

**Issue by kaystrobach** [retspen/webvirtmgr#525]
see http://davidwalsh.name/fullscreen for how to do that ;)

**Comment by brenard** [comment]
Hi, I like this idea. I work on it : https://github.com/brenard/webvirtmgr/commit/6375afb28c4b9443d5840a9311d148e7b609ee43

I will prepare a pull request after some other stuff I want to fix on webvirtmgr-console script.

**Comment by brenard** [comment]
This feature is provided by https://github.com/retspen/webvirtmgr/pull/545.

**Comment by brenard** [comment]
@kaystrobach : could you please close this issue : you could find this feature in master branch.
