### ISSUE TITLE
Security: SSL

### ISSUE THREAD

**Issue by kaystrobach** [retspen/webvirtmgr#526]
You Installation instructions should cover the use of SSL to protect the traffic, as your software is a highly important peace of infrastructure, which is worth gathering the data to penetrate a companies infrastructure :smile: 

Currently it's quite easy to setup SSL for most functions, but the VNC stuff fails for me :angry: 

* There are free certificates available via startssl.com
* you need to configure nginx for ssl (if wanted i can post a sample config)
* what i do not get working is the use of sockets for the www-data user (but ssh is fine)
* needed to change the permissions on the .ssh folder for www-data user

* any hint, what's needed to get the vnc websockets working via nginx as well, port 8000?
** works if if i use manage.py and start the server on a different port :angry:

**Comment by sammcj** [comment]
+1

**Comment by kaystrobach** [comment]
is possible to workaround now ... so closing this issue.

in the meantime i suggest to use ssh to tunnel to the webvirtmgr instance and just allow access from localhost interface!
