### ISSUE TITLE
NoVnc problems

### ISSUE THREAD

**Issue by WhiteIntel** [retspen/webvirtmgr#540]
Hello guys,
I have a big problem regarding novnc (I´m using ubuntu server 14.04):
When I try to connect to a VNC the Chrome developer console tells me "ERROR: CONNECTION REFUSED".

So I checked "netstat -lnp" and registered that the novnc service is not running.

I tried to start it with "sudo service novnc start" but it my system tells me "novnc: unrecognized service
" (novnc is installed!).

After that I tried to run the webvirtmgr-console manually ("sudo /var/www/webvirtmgr/console/webvirtmgr-console") with the following result:

`WARNING:root:No local_settings file found.
Traceback (most recent call last):
  File "/var/www/webvirtmgr/console/webvirtmgr-console", line 33, in <module>
    from websockify import WebSocketProxy
  File "/usr/lib/python2.7/dist-packages/websockify/__init__.py", line 2, in <module>
    from websocketproxy import *
  File "/usr/lib/python2.7/dist-packages/websockify/websocketproxy.py", line 257
    if excepts: raise Exception("Socket exception")
                                                  ^
IndentationError: unindent does not match any outer indentation level`

Can someone tell me what is wrong here?
greetings
Nico

**Comment by brenard** [comment]
Hello,

Your file /usr/lib/python2.7/dist-packages/websockify/websocketproxy.py seam to be modified and an indentation error block it's usage. I mean you have to reinstall websockify package :

<code>apt-get install --reinstall websockify</code>

**Comment by WhiteIntel** [comment]
Thank you, now im able to connect over vnc and spice! :smile:
