### ISSUE TITLE
SPICE Documentation

### ISSUE THREAD

**Issue by catborise** [retspen/webvirtmgr#542]
Hi,
it is specified that with version 4.8.9 spice support was added. Nice upgrade.. thanks
But there is not any configuration example.
when i try to use spice protocol, it says "Unexpected protocol mismatch."

is there any change to work it in supervisord.conf ? or anywhere else...

please help,
thanks

**Comment by brenard** [comment]
Hello,

No, you have nothing to configure or to change in *supervisord.conf*. On the instance page, in *Access / Console type*, you have to choice *spice*. The resulting configuration in XML view is something like that :

    <graphics type='spice' autoport='yes' listen='0.0.0.0'>
      <listen type='address' address='0.0.0.0'/>
    </graphics>

After that, when you open the console page of this instance, webvirtmgr auto-detect that is a SPICE console, and not a VNC console, and display the good one HTML5 client. This client will connect to your instance console throught the websocket of *webvirtmgr-console* script that will act as a proxy to your instance console SPICE TCP socket.

I mean you have a problem in proxying of *webvirtmgr-console* script. I recommend to look in supervisord logs, you could see precious details to understand your problem.

**Comment by catborise** [comment]
thank you very much. the problem is solved.

When i look to the vm config xml file the entry was like below which is default virt-manager vm creation config. 
`<graphics type='spice' autoport='yes'/>`

then i change it like you said it worked flawlessly.

**Comment by lahdekorpi** [comment]
Sorry for the stupid question, but is the SPICE port then binded to the public IP and accessible by anyone, anywhere?
