### ISSUE TITLE
Feature: Show the VM IP

### ISSUE THREAD

**Issue by thiagocpv** [retspen/webvirtmgr#544]
Hi there,

Maybe this is help and show the complete information about the VM.
Show the IP address in the Instance Screen. 

Thanks.

**Comment by SaimonL** [comment]
Yes I need this soo bad.
Some times I just installed a new VM and don't know its I.P address.

**Comment by brenard** [comment]
Hi,

Libvirt does not provide a way to get domain's IP address. Some tips exist to **try** to get this information from the domain name, but it's completely depend of your network topology :

http://stackoverflow.com/questions/19057915/libvirt-fetch-ipv4-address-from-guest

http://blog.oddbit.com/2012/12/15/get-vm-ip/

or use *virt-addr* script in https://github.com/larsks/virt-utils

I mean this feature could be in a *plugin* (I don't know if this webvirtmgr have *plugins*) but I think it's can be properly add in the core project.

**Comment by thiagocpv** [comment]
The dhcp will release the new IP when the O.S start after the installation. This point the pool is configured in the Network section at the WebVirtMgr. Maybe read this information at the dhcp release file or in the arp table should be a solution right now. Something work together with O.S instead with libvirt.

**Comment by retspen** [comment]
New version libvirt already supported getting IP from DHCP but only if that NAT pool in libvirt. How can get IP from bridge device?

**Comment by retspen** [comment]
All scripts will work if webvirtmgr will be installed on the same server where running virtual machines. (arp an etc.)

**Comment by thiagocpv** [comment]
Ok, but this function already released in 4.8.9 ?
I have the webvirtmgr installed on the same server where running my KVM....

**Comment by retspen** [comment]
Only if you use fixed MACs in storage pool

**Comment by thiagocpv** [comment]
I don't understand, what means fixed MACs in storage pool?

**Comment by retspen** [comment]
Sorry - Network pool :-). Create new network pool and checked "Fixed Address". Then open created network pool, copy mac address and create new instance choose the network pull and put the mac which you copied.

**Comment by thiagocpv** [comment]
Ah ok, make sense! I will do tonight!
And talking about networks, I opened the bug about the network #547

Thanks @retspen

**Comment by thiagocpv** [comment]
@retspen I did what you mentioned but I don't see the network mac address in the network screen pool.

(https://cloud.githubusercontent.com/assets/3639439/7330797/e815e890-eacb-11e4-8883-daefe301a553.png)

**Comment by retspen** [comment]
Did you select 'Fixed Address'  when creating network pool?

**Comment by thiagocpv** [comment]
Yes! See the attached

![untitled](https://cloud.githubusercontent.com/assets/3639439/7333389/a28ac5ce-eb44-11e4-88a0-e262c9381323.png)

![untitled1](https://cloud.githubusercontent.com/assets/3639439/7333390/a8864156-eb44-11e4-8898-31b26930f316.png)

**Comment by retspen** [comment]
Need select DHCP, Fixed Address and choose Type Forwarding - NAT.

**Comment by thiagocpv** [comment]
Ahhh, working fine now!
Need set DHCP, Fixed Address, NAT, copy the MAC Address, paste in VM xml and working fine!
Thanks @retspen

**Comment by SaimonL** [comment]
Nice to have a solution finally.
