### ISSUE TITLE
BUG: Network subnet wrong when add 2 or more virtual networks

### ISSUE THREAD

**Issue by thiagocpv** [retspen/webvirtmgr#547]
Hi there!
I was testing subnets configs and I got a bug.
In 'Network' menu I did it:

- I have created a network called customer1 and I configured as:
Network: 192.168.2.0/30 (gateway was auto add as 192.168.2.1 and the broadcast is 192.168.2.3)
DHCP On
IP Start: 192.168.2.2/30 
IP End: 192.168.2.2/30
Forward: ROUTE

Ok so far.....

- I have created other network called customer2 and I configured as:
Network: 192.168.2.4/30 (gateway was auto add as 192.168.2.4 and the broadcast is 192.168.2.7)
DHCP On
IP Start: 192.168.2.5/30 
IP End: 192.168.2.6/30
Forward: ROUTE

The gateway here is wrong! The system should be add the 192.168.2.5 like gateway and not 192.168.2.4. This is network address and not host address.
The DHCP should be start in 192.168.2.6/30 and End 192.168.2.6/30.

Who can test it and report here if the result is the same?

Thanks.

**Comment by retspen** [comment]
Yes you are right problem exist, I will create fix soon as possible.

**Comment by thiagocpv** [comment]
Thank you very much!
