### ISSUE TITLE
network bridge is shutdown from the webvirt networks console but VM is able to ping gateway

### ISSUE THREAD

**Issue by chamambom** [retspen/webvirtmgr#550]
I have deployed device hostbr1 as a bridge network for one of my VM which is part of an existing virtual interface as shown below 

Interface 	hostbr1
IPv4 (static) 	x.x.x.x.x/29
IPv6 (dhcp) 	fe80::221:28ff:fe77:5bf8/64
MAC Adress 	00:21:28:77:5b:f8
Interface type 	bridge
Bridge device 	vnet0
Boot mode 	onboot
State 	

Device 	hostbr1
State 	
Autostart 	
IPv4 configuration
IPv4 Forwarding 	BRIDGE
Network 	None
DHCP 	OFF

I shut down the device hostbr1 hoping that my VM wasnt going to ping the internet but im confused why its able to go to the internet

**Comment by retspen** [comment]
After shutdown check your interface and bridge on host server:

```bash
ifconfig hostbr1
```

```bash
brctl show hostbr1
```

**Comment by chamambom** [comment]
[root@godzilla network-scripts]# ifconfig hostbr1
hostbr1   Link encap:Ethernet  HWaddr 00:21:28:77:5B:F8
          inet addr:X.X.X.X  Bcast:X.X.X.X  Mask:X.X.X.X
          inet6 addr: fe80::221:28ff:fe77:5bf8/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:316259750 errors:0 dropped:0 overruns:0 frame:0
          TX packets:229983239 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:243471034424 (226.7 GiB)  TX bytes:430058214885 (400.5
GiB)

[root@godzilla network-scripts]# brctl show hostbr1
bridge name     bridge id               STP enabled     interfaces
hostbr1         8000.002128775bf8       no              eth2.511
                                                        vnet0
                                                        vnet1
                                                        vnet4
[root@godzilla network-scripts]#

my bridge is tied to a VLAN

**Comment by retspen** [comment]
You have VLAN eth2.511, you need shutdown this physical device and then your VMs can't going to ping the internet.

**Comment by chamambom** [comment]
thanx for the feedback ,so i have to manually shut it down from the host even if the VM network is disabled  for the webvirtmgr interface ............ ?? i thought if you disable the interface from the webvirtmgr then you have disabled all traffic from the VM ?

**Comment by retspen** [comment]
For example: Interface br0 - Bridge device eth1. When I down br0 interface from WebVirtMgr panel libvirt down physical interface eth1. Your bridge device vnet0 like virtual interface not physical.

**Comment by chamambom** [comment]
i see. so from the webvirtmgr panel i will be bringing down a virtual
interface only ,that is why i am able to ping the internet ........ via the
phyiscal .i think i can understand it now
