### ISSUE TITLE
debian 8  * ERROR: /etc/default/libvirt-bin not found. Exiting...

### ISSUE THREAD

**Issue by la0wei** [retspen/webvirtmgr#553]
already apt-get isntall libvirt-bin
then
wget -O - http://retspen.github.io/libvirt-bootstrap.sh | sudo sh
but error
* ERROR: /etc/default/libvirt-bin not found. Exiting...

there's no libvirt-bin in  /etc/default/

**Comment by brenard** [comment]
Hi,

Libvirt-bin service was rename in Debian Jessie, it's now libvirtd provide by _libvirt-daemon-system_ debian package. This libvirt-bootstrap.sh script was designed for Debian Wheezy.

**Comment by la0wei** [comment]
Yes,that's what I'm talking aboot.I googled but found nothing could help.Could you please update the script?

**Comment by brenard** [comment]
Could you check it : 

https://gist.github.com/brenard/e991eb4cbfab1d686501

**Comment by la0wei** [comment]
First thanks for your help!
2nd,maybe you know in China,a firewall blocked us to visit foreign websites.I can visit the github root domain,but not gist.github.com.
So I could not response the consequence ASAP,I will find a proxy to check it,and post the result tomorrow morning(China UTC+8).
Thanks!

**Comment by JimyKK** [comment]
Just gave this script a go myself and it apears to work. I'll report back when I have finished the complete setup.

**Comment by la0wei** [comment]
This script works!
But I still have other problems.Maybe I should instlall Debian 7 instead.
Thanks all  the same!

**Comment by brenard** [comment]
@JimyKK : thank for your report, I fix script, it's now add correctly _"-l"_ parameter to _libvirtd_opts_.

@retspen : could you update the published script ?

**Comment by retspen** [comment]
Big thanks @brenard , I updated the script.
