### ISSUE TITLE
webinterface only working when starting Django manually

### ISSUE THREAD

**Issue by undee123** [retspen/webvirtmgr#555]
Hi!

I've set up webvirtmgr on Ubuntu 14.04.2 LTS and it works fine, but only if I start Django manually with 

./manage.py runserver 0:8000

I use Apache2 as webserver with the following configuration file:

WSGISocketPrefix /var/run/apache2/wsgi
VirtualHost *:8080>
    ServerAdmin webmaster@dummy-host.example.com
    ServerName meinserver.xx

    WSGIDaemonProcess webvirtmgr display-name=%{GROUP} python-path=/var/www/webvirtmgr
    WSGIProcessGroup webvirtmgr
    WSGIScriptAlias / /var/www/webvirtmgr/webvirtmgr/wsgi.py

    Alias /static /var/www/webvirtmgr/webvirtmgr/static/
    Alias /media /var/www/webvirtmgr/webvirtmgr/media/

    <Directory /var/www/webvirtmgr/webvirtmgr>
        <Files wsgi.py>
            Order deny,allow
            Allow from all
        </Files>
    </Directory>

    CustomLog ${APACHE_LOG_DIR}/webvirtmgr-access_log common
    ErrorLog ${APACHE_LOG_DIR}/webvirtmgr-error_log
</VirtualHost

I don't understand what I have to do to make Django start when it's needed and not just manually. Andone could give me a hint for this?

Thank you very much!!!

**Comment by retspen** [comment]
Add

<code>WSGIPythonPath /var/www/webvirtmgr</code>

after

<code>WSGIScriptAlias / /var/www/webvirtmgr/webvirtmgr/wsgi.py</code>

**Comment by undee123** [comment]
Hi,

when I do that apache2 says "WSGIPythonPath cannot occur within <VirtualHost> section" and won't start.
I tried put this line before <Virtualhost>, the apache2 starts, but I still get a "ERR_CONNECTION_REFUSED" from Chrome browser.

**Comment by undee123** [comment]
Ok, now I've seen the following in the logs when I restart apache2:

error.log:

[Fri May 15 08:02:05.229160 2015] [:error] [pid 22212:tid 140228962477952] Exception ignored in: <module 'threading' from '/usr/lib/python3.4/threading.py'>
[Fri May 15 08:02:05.229160 2015] [:error] [pid 22211:tid 140228962477952] Exception ignored in: <module 'threading' from '/usr/lib/python3.4/threading.py'>
[Fri May 15 08:02:05.229190 2015] [:error] [pid 22212:tid 140228962477952] Traceback (most recent call last):
[Fri May 15 08:02:05.229194 2015] [:error] [pid 22211:tid 140228962477952] Traceback (most recent call last):
[Fri May 15 08:02:05.229196 2015] [:error] [pid 22212:tid 140228962477952]   File "/usr/lib/python3.4/threading.py", line 1288, in _shutdown
[Fri May 15 08:02:05.229199 2015] [:error] [pid 22211:tid 140228962477952]   File "/usr/lib/python3.4/threading.py", line 1288, in _shutdown
[Fri May 15 08:02:05.229496 2015] [:error] [pid 22211:tid 140228962477952]     assert tlock is not None
[Fri May 15 08:02:05.229498 2015] [:error] [pid 22212:tid 140228962477952]     assert tlock is not None
[Fri May 15 08:02:05.229503 2015] [:error] [pid 22211:tid 140228962477952] AssertionError:
[Fri May 15 08:02:05.229512 2015] [:error] [pid 22212:tid 140228962477952] AssertionError:
[Fri May 15 08:02:05.239300 2015] [mpm_event:notice] [pid 22207:tid 140228962477952] AH00491: caught SIGTERM, shutting down
[Fri May 15 08:02:06.274863 2015] [mpm_event:notice] [pid 22353:tid 139926236125056] AH00489: Apache/2.4.7 (Ubuntu) mod_wsgi/3.4 Python/3.4.0 configured -- resuming normal operations
[Fri May 15 08:02:06.274910 2015] [core:notice] [pid 22353:tid 139926236125056] AH00094: Command line: '/usr/sbin/apache2'


webvirtmgr-error.log:
[Fri May 15 08:02:05.255560 2015] [:error] [pid 22210:tid 140228962477952] Exception ignored in: <module 'threading' from '/usr/lib/python3.4/threading.py'>
[Fri May 15 08:02:05.255599 2015] [:error] [pid 22210:tid 140228962477952] Traceback (most recent call last):
[Fri May 15 08:02:05.255605 2015] [:error] [pid 22210:tid 140228962477952]   File "/usr/lib/python3.4/threading.py", line 1288, in _shutdown
[Fri May 15 08:02:05.255911 2015] [:error] [pid 22210:tid 140228962477952]     assert tlock is not None
[Fri May 15 08:02:05.255919 2015] [:error] [pid 22210:tid 140228962477952] AssertionError:

**Comment by undee123** [comment]
I've updated mod-wsgi to 3.4 now, but nothing changed :-(

**Comment by retspen** [comment]
I tested apache2 and mod_wsgi - work without problem. 

```txt
<VirtualHost *:8080>
    ServerAdmin webmaster@myhost.com
    ServerName myhost.com

    WSGIDaemonProcess webvirtmgr display-name=%{GROUP} python-path=/var/www/webvirtmgr
    WSGIProcessGroup webvirtmgr
    WSGIScriptAlias / /var/www/webvirtmgr/webvirtmgr/wsgi.py

    Alias /static /var/www/webvirtmgr/webvirtmgr/static/
    Alias /media /var/www/webvirtmgr/webvirtmgr/media/

    <Directory /var/www/webvirtmgr/webvirtmgr>
        <Files wsgi.py>
            Order deny,allow
            Allow from all
        </Files>
    </Directory>

    CustomLog ${APACHE_LOG_DIR}/webvirtmgr-access_log common
    ErrorLog ${APACHE_LOG_DIR}/webvirtmgr-error_log
</VirtualHost>
```

Installed package: apache2 and libapache2-mod-wsgi

**Comment by undee123** [comment]
Hi retspen,

the change in ports.conf did it! Couldn't find this step in the wiki, maybe you could add it?

Thank you very much!

Andy

**Comment by retspen** [comment]
First version WebVirtMgr worked on Apache with mod_wsgi but always went down or hung.
