### ISSUE TITLE
Server disconnected (code: 1006) after 20 seconds

### ISSUE THREAD

**Issue by ITFactoryAUT** [retspen/webvirtmgr#556]
Hello folks,
I know there was an issue with the same problem some months ago, but I cant find it.
@brenard said that he did a pull request to a python library that is causing the problem.
Is there any progress yet on this issue?

Have a nice day & greetings
Nico

**Comment by brenard** [comment]
Hi,

@bkanuka propose an fix to websockify project (https://github.com/kanaka/websockify/issues/166) and it was merged. Could you check with upstream version of websockify ?

Futhermore, this issue is duplicated #503. Could you close it and continue with us on #503 ?

**Comment by ITFactoryAUT** [comment]
Sorry for that, I commented the reference one ;)
