### ISSUE TITLE
When i clone an image via the webGUI i get 504 Gateway Time-out nginx/1.0.15

### ISSUE THREAD

**Issue by chamambom** [retspen/webvirtmgr#566]
When i clone an image via the webGUI i get 504 Gateway Time-out nginx/1.0.15 , i have tried to play around with the Nginx timeout settings to no avail

AND PLEASE NOTE THAT THE IMAGE ACTUALLY GETS CLONED , JUST THE ERROR MESSAGE

**Comment by retspen** [comment]
File: gunicorn.conf.py Variable: timeout
