### ISSUE TITLE
VNC is broken when webvirtmgr is hosted on a HTTPS webserver

### ISSUE THREAD

**Issue by tecnobrat** [retspen/webvirtmgr#58]
These lines of code in templates/vnc.html causes VNC to fail to connect if you are using apache over HTTPS.

``` javascript
                       'encrypt':      WebUtil.getQueryVar('encrypt',
                                (window.location.protocol === "https:")),
```

I replaced it with:

``` javascript
                       'encrypt':      false,
```

And then VNC showed properly and I have no more issues.

**Comment by srulikuk** [comment]
I had webvirtmgr working for a while and decided to use https, i updated templates/console.html as above, I also updated webvirtmgr-novnc cert variable as above.
The webvirtmgr page is working fine but the vnc page chrome shows "the page is trying to load scripts from unauthenticated sources" it gives me a option to "load unsafe scripts" and page displays properly, I am just wondering what this error is and what I can do in webvirtmgr to sort it

**Comment by brenard** [comment]
I mean it's just that your are using an "unsafe" certificate for your webvirt-novnc script. You have to use a certificate that is know as safe by your browser. You could try also to access with your browser to https://[web.virt.mgr.host]:6080 and add permanently a security exception for this couple of host and port.

**Comment by srulikuk** [comment]
the certificate is a comodo certificate, no errors on other pages or in main webvirtmgr page, the error only appears in vnc popup page, it states the certificate is valid (green lock symbol) however for the encryption it states there connection is secure but includes resources that are not.

**Comment by brenard** [comment]
Do you try to set the WS_PUBLIC_HOST in local_settings.py ? This parameter (appear in last version) permit to control the hostname of webservice host. It's important that the hostname of the WS host corresponding with the subject of your certificate.

**Comment by srulikuk** [comment]
i do not have a local_settings.py but I did make the changes shown here https://github.com/brenard/webvirtmgr/commit/731bc3304bb319656a7c1f90d9d858be736a06f5 I still have the same issue, I also looked and did not find documentation how to upgrade to the latest version of  webvirtmgr, is there documentation somewhere?

**Comment by brenard** [comment]
If you don't have local_settings.py file, you could do this modification in settings.py (like in brenard@731bc33). In any case, the WS_PUBLIC_HOST variable must be set with the value of the CN field of your certificate.

**Comment by srulikuk** [comment]
in settings.py i added the line WS_PUBLIC_HOST = mydomain.com which is same as in certificate (the certificate actually has many domains) and i still have the same issue

**Comment by srulikuk** [comment]
after adding the setting WS_PUBLIC_HOST = mydomain.com i get a timeout error on vnc and cant connect. this si my output when trying to restart / stop novnc
# service webvirtmgr-novnc stop
 * Stopping WebVirtMgr NoVNC proxy webvirtmgr-novnc                                                                                 start-stop-daemon: warning: failed to kill 1351: No such process
when I try to start it it gives an ok but running service status tells me its not running, my output from /var/www/webvirtmgr/console/webvirtmgr-novnc results in;
Traceback (most recent call last):
  File "/var/www/webvirtmgr/console/webvirtmgr-novnc", line 20, in <module>
    from webvirtmgr.settings import WS_PORT
  File "/var/www/webvirtmgr/webvirtmgr/settings.py", line 149, in <module>
    WS_PUBLIC_HOST = mydomain.com
NameError: name 'mydomain' is not defined

**Comment by brenard** [comment]
You have to put mydomain.com in quotes :

    WS_PUBLIC_HOST = "mydomain.com"

**Comment by srulikuk** [comment]
when I do that and webvirtmgr-novnc still does not run, i get the follwoing
# /var/www/webvirtmgr/console/webvirtmgr-novnc
WARNING:root:No local_settings file found.
WebSocket server settings:
  - Listen on 0.0.0.0:6080
  - Flash security policy server
  - No SSL/TLS support (no cert file)
Traceback (most recent call last):
  File "/var/www/webvirtmgr/console/webvirtmgr-novnc", line 161, in <module>
    server.start_server()
  File "/usr/lib/python2.7/dist-packages/websockify/websocket.py", line 751, in start_server
    lsock = self.socket(self.listen_host, self.listen_port, False, self.prefer_ipv6)
  File "/usr/lib/python2.7/dist-packages/websockify/websocket.py", line 193, in socket
    sock.bind(addrs[0][4])
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use

The cert file is in the correct location as the regular pages open properly with https.

thanks you so much for helping me with this

**Comment by brenard** [comment]
Your error is :

     [Errno 98] Address already in use

That mean that another process is currently listening on TCP port 6080. If you install novnc Debian package, it's possible that novnc service is currently running. In this case, you have to stop and disable novnc service :

    service novnc stop
    insserv -r novnc

After that, try to restart supervisord. If you still have this problem after stopping novnc, try to detect witch process is listening on 6080 TCP port by running as root :

    netstat -lnp|grep 6080

**Comment by srulikuk** [comment]
I am using ubuntu, novnc is not installed, i restarted nginx and was able to start webvirtmgr-novnc however i still get the same error for https on novnc dialog, see following links to screenshot, http://pbrd.co/1MwXOrX you will see main page https green lock. once i click on vnc dilaog i get the following http://pbrd.co/1MwXSYH, after i click load unsafe scripts page loads but https gets red with strikeout

**Comment by retspen** [comment]
Can you do this:
```bash
sudo fuser -k 6080/tcp
```

and then restart supervisor:
```bash
sudo service supervisor restart
```

**Comment by brenard** [comment]
Look in the source code of VNC console page : I mean you have JS script load with http://~~~ hard code URL. This URL is normaly defined by using STATIC_URL (in settings.py file) variable but I don't known witch version of webvirtmgr you are using. if you can, you should upgrade your installation.

**Comment by srulikuk** [comment]
Result
fuser -k 6080/tcp
6080/tcp:            13174
Still same result in web page

**Comment by retspen** [comment]
@brenard What js file do you mean?

**Comment by srulikuk** [comment]
i see STATIC_URL = '/static/' in settings.py but cant see http reference in *webvirtmgr-novnc, with regards to upgrading, I have version 4.8.8 I would like to upgrade but i cannot find any documentation on how to upgrade.

many thanks

**Comment by retspen** [comment]
```bash
cd /var/www/webvirtmgr/; git pull
```

**Comment by brenard** [comment]
@retspen : I mean about novnc/util.js JS file and all others call using Util.load_scripts() method ("webutil.js", "base64.js", "websock.js", "des.js", "input.js", "display.js", "jsunzip.js", "rfb.js").

@srulikuk : Try an upgrade and if you still have problem, send us the HTML code of VNC console page.

**Comment by srulikuk** [comment]
I removed my changed files and made a git pull, now i cant login as its not configured for https and ngix is forcing https.
What are all the steps i need to do to get https working, please correct me if i miss something?
1. change encrypt to false as in https://github.com/retspen/webvirtmgr/issues/58#issue-14656089
2. configure certificate path as in https://github.com/retspen/webvirtmgr/issues/58#issuecomment-29558727
3. configure WS_PUBLIC_HOST as in https://github.com/brenard/webvirtmgr/commit/731bc3304bb319656a7c1f90d9d858be736a06f5

**Comment by brenard** [comment]
My advice is to create an local_settings.py in webvirtmgr/local/ directory by copying local_settings.py.example. In this file you have to configure :

    WS_PUBLIC_HOST='mydomain.com'
    WS_CERT = '/path/to/mydomain.com.pem'

You don't have to modify console template as explain here : https://github.com/retspen/webvirtmgr/issues/58#issue-14656089 This parameter is automatically use encrypt access to WS.

**Comment by srulikuk** [comment]
1. novonc only works when I run /var/www/webvirtmgr/console/webvirtmgr-console as soon as i ctrl C it it stops working, is it a new service in latest version that i need to start?
2. https works fine novnc dialog displays correctly, however there is still a notification about scripts from unauthenticated sources, but i do not have to load it for vnc to display

**Comment by brenard** [comment]
As explain here https://github.com/retspen/webvirtmgr/wiki/Install-WebVirtMgr , you have to configure supervisord to manage webvirtmgr-console service for you. Concerning the notification about scripts from unauthenticated sources, as explain before, give us the HTML code of your VNC console web page.

**Comment by srulikuk** [comment]
I updated the supervisor script as in guide, now vnc gives error 1006, when I try /var/www/webvirtmgr/console/webvirtmgr-console, i get error 
WebSocket server settings:
  - Listen on 0.0.0.0:6080
  - Flash security policy server
  - SSL/TLS support
Traceback (most recent call last):
  File "/var/www/webvirtmgr/console/webvirtmgr-console", line 218, in <module>
    server.start_server()
  File "/usr/lib/python2.7/dist-packages/websockify/websocket.py", line 751, in start_server
    lsock = self.socket(self.listen_host, self.listen_port, False, self.prefer_ipv6)
  File "/usr/lib/python2.7/dist-packages/websockify/websocket.py", line 193, in socket
    sock.bind(addrs[0][4])
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use

however when I stop supervisor service this command does not give an error (obviously cant log into to webpage with supervisor stopped)

netstat -lnp|grep 6080
tcp        0      0 0.0.0.0:6080            0.0.0.0:*               LISTEN      22221/python   

however while supervisor stopped netstat -lnp|grep 608 returns no result

**Comment by srulikuk** [comment]
also when i execute service webvirtmgr-console status, i get 
webvirtmgr-console: unrecognized service

**Comment by brenard** [comment]
Restart service using supervisor and check your log files in /var/log/supervisor/ when you access to the VNC console. It's normal that "service webvirtmgr-console status" command return this command because  the webvirtmgr-console does not exist. The right service is supervisor.

**Comment by srulikuk** [comment]
this is what i get in webvirtmgr-console log
WebSocket server settings:
  - Listen on 0.0.0.0:6080
  - Flash security policy server
  - No SSL/TLS support (no cert file)
  - proxying from 0.0.0.0:6080 to ignore:ignore

  1: xx.xx.xx.xx: SSL connection but '/etc/nginx/ssl/mydomain.co.uk.pem' not found
  2: xx.xx.xx.xx: SSL connection but '/etc/nginx/ssl/mydomain.co.uk.pem' not found

the pem file is there i also changed owner to www-data but does not help

**Comment by srulikuk** [comment]
Since the update I dont have VNC access to my VM's, I am really desperate, what can I do about this error?

**Comment by srulikuk** [comment]
Solved the certificate problem, the certificate has to be in /webvirtmgr dir, in version 4.8.8 it did not, also the regular pages (main webvirtmgr not vnc) did not have a problem that the cert was in /etc/nginx/ssl/ 

regarding the VNC html, are you referring to templates/console-vnc.html? if yes i pasted it here http://pastebin.com/9dkLp6Ry

**Comment by srulikuk** [comment]
Did you have a chance to look at my html yet?
