### ISSUE TITLE
question about how to learn webvirtmgr

### ISSUE THREAD

**Issue by Robin-Lin** [retspen/webvirtmgr#618]
I have no experience in KVM, libvirt, gunicorn, just know something about linux, python and Django. How could I study webvirtmgr well?  Following official documents and google, I have installed webvirtmgr on ubuntu12.04 and created a local VM. But now, I am confused due to the official documents lacking. I don't konw how to learn it well. Can someone give me some advice? Thanks.

**Comment by Azendale** [comment]
I don't know that a bug report is a good place to get support, but I don't really know of a better place yet.

Is there a specific reason that you used 12.04? There's a much newer stable version of Ubuntu, 16.04. Not that 12.04 wouldn't work -- just that if you are setting up stuff from scratch, there's no reason not to use 16.04.

What were you hoping to learn with webvirtmgr? What kind of use cases were you hoping to use it for? In a corporate environment with multiple networks? A home lab? 

Saying that you want to learn a system is a very vague goal. It would be a good idea to be more specific by saying what you want to learn to do with WebVirtMgr. Something like "I want to learn how to do a two system setup with Live Migrations" or "I want to learn how to use Ceph and WebVirtMgr together".
