### ISSUE TITLE
Error 500 Internal error

### ISSUE THREAD

**Issue by euronck** [retspen/webvirtmgr#622]
restart the supervisor, ngnix still not coming up

**Comment by rokclimb15** [comment]
Can you post logs from nginx?

**Comment by euronck** [comment]
please close this rockclimb i had to rebuild the box.

**Comment by Azendale** [comment]
euronck, since we are not owners of the project, neither I nor rokclimb15 would be able to close this ticket. But since you were the one who opened it, you can close it.

**Comment by euronck** [comment]
Azendale... closing.
