### ISSUE TITLE
fail to create new interface without err log

### ISSUE THREAD

**Issue by hjfeng1988** [retspen/webvirtmgr#646]
![qq 20170915090823](https://user-images.githubusercontent.com/8954783/30462036-6c5d30b0-99f5-11e7-98fc-3f8f49fe9796.png)

After i click create button,there is no new netcard interface,no error message.
I can't found any error log on host server,the same result on webvirtmgr server.Which i look for the log file is /var/log/message and /var/log/libvirt,I also debug the webvirtmgr log with command `./manage.py runserver 0:8000`,but it return me normal nginx access log.
Is there any other way to debug the error.

operating system:CentOS 7.3
webvirtmgr version:4.8.9

**Comment by Mrlk** [comment]
oh, I have this problem to....

**Comment by FanFansfan** [comment]
表单的后端验证逻辑有问题，webvirtcloud好像有所改进

**Comment by hjfeng1988** [comment]
已经改用xen
