### ISSUE TITLE
guest has not initialize the display (yet)

### ISSUE THREAD

**Issue by ucasfeng** [retspen/webvirtmgr#692]
when connect to instance created by webvirtmgr, it shows.

![image](https://user-images.githubusercontent.com/39721431/96569439-b8b6a180-12fb-11eb-9460-e07a29e2b369.png)

can anybody tell me how to slove the problem?

**Comment by catborise** [comment]
You can check it with virt-manager. Vnc or spice device may not be added to the vm.
Install virt-manager to your host to see if it is running as expected

**Comment by ucasfeng** [comment]
after install novnc, it works normally. thank you.
